from typing import Protocol
from uuid import UUID

from modules.mir.domain.entities.mir import MIR


class MirRepository(Protocol):
    async def create_mir(self, mir: MIR) -> MIR: ...

    async def update_mir(self, mir: MIR) -> MIR: ...

    async def delete_mir(self, mir_id: UUID, actor_id: UUID) -> None: ...

    async def get_mir_all(self) -> list[MIR]: ...

    async def get_by_codigo_mir(self, codigo_mir: str) -> MIR | None: ...

    async def get_by_id(self, mir_id: UUID) -> MIR | None: ...
