from typing import Protocol
from uuid import UUID

from modules.mir.domain.entities.mir import MIR
from modules.mir.domain.Enum.estado import Estado


class MirRepository(Protocol):
    async def create_mir(self, mir: MIR) -> MIR: ...

    async def update_mir(self, mir: MIR) -> MIR: ...

    async def delete_mir(self, mir_id: UUID, actor_id: UUID) -> None: ...

    async def get_mir_all(self, detectada_por_id: UUID | None = None) -> list[MIR]: ...

    async def reservar_numero(self, anio: int) -> int: ...

    async def get_by_codigo_mir(self, codigo_mir: str) -> MIR | None: ...

    async def get_by_id(self, mir_id: UUID) -> MIR | None: ...

    # Este lo vamos a usar para filtrar por estado para los distintos roles
    async def filtrar_estado(self, estado: Estado) -> list[MIR]: ...

    async def editar_estado(self, mir_id: UUID, estado: Estado) -> MIR: ...