/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/usuarios': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Listar Usuarios Activos */
    get: operations['listar_usuarios_activos_usuarios_get']
    put?: never
    /** Crear Usuario */
    post: operations['crear_usuario_usuarios_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/usuarios/{correo}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Consultar Usuario Por Correo */
    get: operations['consultar_usuario_por_correo_usuarios__correo__get']
    put?: never
    post?: never
    /** Dar Baja Usuario Existente */
    delete: operations['dar_baja_usuario_existente_usuarios__correo__delete']
    options?: never
    head?: never
    /** Actualizar Usuario Existente */
    patch: operations['actualizar_usuario_existente_usuarios__correo__patch']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ActualizarUsuarioDTO */
    ActualizarUsuarioDTO: {
      /** Rol */
      rol?: string | null
      /** Departamento */
      departamento?: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** RegistrarUsuarioDTO */
    RegistrarUsuarioDTO: {
      /** Correo */
      correo: string
      /** Rol */
      rol: string
      /** Departamento */
      departamento: string
      /** Activo */
      activo: boolean
      /**
             * Creado En
             * Format: date-time
             */
      creado_en: string
    }
    /**
         * Rol
         * @description Catálogo cerrado de roles del PG09 §1.1.
         * @enum {string}
         */
    Rol: 'DETECTOR' | 'JEFE_CLD' | 'TECNICO_CLD' | 'RESPONSABLE_RESOLUCION' | 'EJECUTOR' | 'RSGI'
    /** UsuarioRead */
    UsuarioRead: {
      /**
             * Id
             * Format: uuid
             */
      id: string
      /** Correo */
      correo: string
      rol: components['schemas']['Rol']
      /** Departamento */
      departamento: string
      /** Activo */
      activo: boolean
      /**
             * Creado En
             * Format: date-time
             */
      creado_en: string
      /** Dado De Baja En */
      dado_de_baja_en: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  listar_usuarios_activos_usuarios_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsuarioRead'][]
        }
      }
    }
  }
  crear_usuario_usuarios_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegistrarUsuarioDTO']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsuarioRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  consultar_usuario_por_correo_usuarios__correo__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        correo: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsuarioRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  dar_baja_usuario_existente_usuarios__correo__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        correo: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  actualizar_usuario_existente_usuarios__correo__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        correo: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ActualizarUsuarioDTO']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsuarioRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
