"""contador codigo

Revision ID: 7e02b76afe5a
Revises: 9a3745131397
Create Date: 2026-09-23 12:27:51.859680

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e02b76afe5a"
down_revision: str | Sequence[str] | None = "9a3745131397"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mir_codigo_contadores",
        sa.Column("anio", sa.Integer(), nullable=False),
        sa.Column("ultimo_numero", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("anio"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mir_codigo_contadores")
    # ### end Alembic commands ###
