"""initial schema

Revision ID: 9a3745131397
Revises:
Create Date: 2026-09-23 12:24:30.026122

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a3745131397"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documentos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("PDF", "WORD", "EXCEL", "IMAGEN", "OTRO", name="tipo_documento"),
            nullable=False,
        ),
        sa.Column("storage_id", sa.String(), nullable=False),
        sa.Column("creado_por", sa.UUID(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("correo", sa.String(), nullable=False),
        sa.Column("rol", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("departamento", sa.String(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dado_de_baja_en", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_correo"), "usuarios", ["correo"], unique=True)
    op.create_table(
        "mirs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("codigo_mir", sa.String(length=16), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("MEJORA", "INCIDENCIA", "RECLAMACION", name="tipo_mir"),
            nullable=False,
        ),
        sa.Column(
            "estado",
            sa.Enum(
                "EN_REVISION",
                "EN_PROGRESO",
                "COMPLETADA",
                "RECHAZADA",
                "TERMINADA",
                name="estado_mir",
            ),
            nullable=False,
        ),
        sa.Column("detectada_por_id", sa.UUID(), nullable=False),
        sa.Column("solucionado", sa.Boolean(), nullable=False),
        sa.Column("solucion_adoptada", sa.Text(), nullable=True),
        sa.Column("analisis_causas", sa.Text(), nullable=True),
        sa.Column("algo_mas_que_hacer", sa.Text(), nullable=True),
        sa.Column(
            "prioridad",
            sa.Enum("BAJA", "MEDIA", "ALTA", name="prioridad_mir"),
            nullable=True,
        ),
        sa.Column("tecnico_cld_id", sa.UUID(), nullable=True),
        sa.Column("responsable_resolucion_id", sa.UUID(), nullable=True),
        sa.Column("ejecutor_id", sa.UUID(), nullable=True),
        sa.Column(
            "fecha_prevista_resolucion", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "fecha_comprobacion_eficacia", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("resultado_comprobacion_eficacia", sa.Text(), nullable=True),
        sa.Column("fecha_deteccion", sa.Date(), nullable=True),
        sa.Column("empresa_nombre", sa.String(length=255), nullable=True),
        sa.Column("persona_contacto", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=50), nullable=True),
        sa.Column("correo_electronico", sa.String(length=320), nullable=True),
        sa.Column("nombre_comercial", sa.String(length=255), nullable=True),
        sa.Column("codigo_cliente", sa.String(length=100), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modificado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("borrado", sa.Boolean(), nullable=False),
        sa.Column("borrado_por_id", sa.UUID(), nullable=True),
        sa.Column("borrado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["detectada_por_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ejecutor_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsable_resolucion_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tecnico_cld_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_mir"),
    )
    op.create_table(
        "mir_documentos",
        sa.Column("mir_id", sa.UUID(), nullable=False),
        sa.Column("documento_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["documento_id"], ["documentos.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["mir_id"], ["mirs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("mir_id", "documento_id"),
        sa.UniqueConstraint("documento_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mir_documentos")
    op.drop_table("mirs")
    op.drop_index(op.f("ix_usuarios_correo"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_table("documentos")
    # ### end Alembic commands ###
