"""add nombre to usuarios

Revision ID: d2ada575cfde
Revises: 1ad451f3955c
Create Date: 2026-09-17 09:59:32.911238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ada575cfde'
down_revision: Union[str, Sequence[str], None] = '1ad451f3955c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nombre', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nombre')
    # ### end Alembic commands ###
